/******************************************
Hello.java
Aimaiti nadiya
Aug,19,2020
CMSC255,003
*****************************************/
public class Hello{
	public static void main(String[]args){
	System.out.println("<Nadiya>");
	System.out.println("<Hello.java.>");
	System.out.println("<print out name>");
	System.out.println("<Aug,19,2020>");
	System.out.println("<CMSC255,003>");
	System.out.println();
}
}
